##
## EPITECH PROJECT, 2019
## OOP_arcade_2018
## File description:
## Makefile
##

all:
	make -C ./snake
	make -C ./centipede

clean:
	make clean -C ./snake
	make clean -C ./centipede

fclean:
	make fclean -C ./snake
	make fclean -C ./centipede

re: fclean all